[package]
name = "native"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
flutter_rust_bridge = "=2.10.0"
lazy_static = "1.5.0"
memmap2 = "0.9.8"
lru = "0.16.1"
chrono = "0.4.41"
parking_lot = "0.12.4"
walkdir = "2.5.0"
rand = "0.9.2"
windows = { version = "0.58.0", features = ["Media_Playback", "Storage", "Storage_Streams", "Storage_FileProperties"] }